Lesson4
ruslan-yandiev/Advanced_Javascript pull request #5
Opened 2020-06-04 00:47 UTC by ruslan-yandiev

2020-06-04 16:14 UTC, index01d requested changes

2020-06-04 16:14 UTC, index01d commented on lesson4/first_task/app.js
> +        let child = node.childNodes[i];
Автор наверно имел ввиду использовать не только childNodes, но раз есть showDomTree4, то пойдёт :)

2020-06-04 16:14 UTC, index01d commented on lesson4/second_task/fcs.js
> +        complete = (flight.registartionEnds < nowTime) ? true : false,
тернарный оператор здесь и выше выглядят как-то неуместно. Можно оставить просто условие
на строчку выше в 211 можно просто инвертировать условие (https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%BA%D0%BE%D0%BD%D1%8B_%D0%B4%D0%B5_%D0%9C%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B0)

2020-06-04 16:14 UTC, index01d commented on lesson4/first_task/app.js
> +'use strict'
вероятно стоит прибрать null в конце каждой строчке в выводе в консоль.

2020-06-05 14:49 UTC, ruslan-yandiev commented on lesson4/first_task/app.js
> +        let child = node.childNodes[i];
Немного не понял, на счет автора и что он имел ввиду. Если на счет того, что пример взят у другого автора, то я взял два решения у сторонних авторов и переделал под себя. В итоге быстрее было бы просто самому придумать. Что-то не понравилось это задание, пришлось силой себя заставлять, что-то делать.

2020-06-05 14:49 UTC, ruslan-yandiev commented on lesson4/second_task/fcs.js
> +        complete = (flight.registartionEnds < nowTime) ? true : false,
А ведь и в правду масло масляное получается ))

2020-06-05 16:55 UTC, index01d approved these changes

2020-06-05 16:55 UTC, index01d commented on lesson4/first_task/app.js
> +    console.log(' '.repeat(step), node.nodeName, chengeNull(node.nodeValue));
лучше наверно было вынести функцию вывода результата, принимающую node и step, которая делала бы  `console.log(' '.repeat(step), node.nodeName, node.nodeValue || '')`, таким образом не дублировалась бы логика вывода узла

2020-06-05 17:59 UTC, ruslan-yandiev commented on lesson4/first_task/app.js
> +    console.log(' '.repeat(step), node.nodeName, chengeNull(node.nodeValue));
Думал об этом. Реализую.

2020-06-05 18:48 UTC, merged